export const EntryData = [
  {
    id: 0,
    value: "nama",
    label: "perfumeNamelbl",
    type: "text",
  },
  {
    id: 1,
    value: "harga",
    label: "perfumePricelbl",
    type: "text",
  },
  {
    id: 2,
    value: "brand",
    label: "perfumeBrandlbl",
    type: "text",
  },
  {
    id: 3,
    value: "tipe_aroma",
    label: "scentTypelbl",
    type: "text",
  },
  {
    id: 4,
    value: "tipe_parfum",
    label: "perfumeTypelbl",
    type: "text",
  },
  {
    id: 5,
    value: "kategori",
    label: "Kategori",
    type: "text",
  },
  {
    id: 6,
    value: "deskripsi",
    label: "desclbl",
    type: "text",
  },
  {
    id: 7,
    value: "quality_index",
    label: "qualityIndexlbl",
    type: "number",
  },
  {
    id: 8,
    value: "durability_index",
    label: "durabilityIndexlbl",
    type: "number",
  },
  {
    id: 9,
    value: "aroma_index",
    label: "scentIndexlbl",
    type: "number",
  },
  {
    id: 10,
    value: "price_index",
    label: "priceIndexlbl",
    type: "number",
  },
  {
    id: 11,
    value: "ukuran",
    label: "sizelbl",
    type: "text",
  },
  {
    id: 12,
    value: "link_pembelian",
    label: "link",
    type: "text",
  },
];
